---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  labels:
    app.kubernetes.io/name: cert-manager
  name: cert-manager-webhook-ca
  namespace: cert-manager
spec:
  ca:
    secretName: cert-manager-webhook-ca
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  labels:
    app.kubernetes.io/name: cert-manager
  name: cert-manager-webhook-selfsign
  namespace: cert-manager
spec:
  selfsigned: {}
...
