apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app.kubernetes.io/component: webhook-ca-sync
    app.kubernetes.io/name: cert-manager
  name: cert-manager-webhook-ca-sync
  namespace: cert-manager
spec:
  backoffLimit: 20
  template:
    metadata:
      labels:
        app.kubernetes.io/component: webhook-ca-sync
        app.kubernetes.io/name: cert-manager
    spec:
      serviceAccountName: cert-manager-webhook-ca-sync
      restartPolicy: OnFailure
      containers:
      - name: ca-helper
        image: quay.io/munnerz/apiextensions-ca-helper:v0.1.0
        imagePullPolicy: IfNotPresent
        args:
        - -config=/config/config
        volumeMounts:
        - name: config
          mountPath: /config
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            cpu: 100m
            memory: 128Mi
      volumes:
      - name: config
        configMap:
          name: cert-manager-webhook-ca-sync
