apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: webhook
    app.kubernetes.io/name: cert-manager
  name: cert-manager-webhook
  namespace: cert-manager
spec:
  type: ClusterIP
  ports:
  - name: https
    port: 443
    targetPort: 6443
  selector:
    app.kubernetes.io/component: webhook
    app.kubernetes.io/name: cert-manager
